// @file preferences.js
var Preferences = {
    toMonitor: false,
    passwordGrant:true,
    enableSMS: true,
    enableChat: true,
    enablePresence: true,
    enableAddressBook: true,
    enableVoice: false,
    baseUrl: "baseurl.domain.com",
    projectName: "PUB-project.name",
    username: "user1@domain.com",
    password: "Test@123",
    privateKey:  "PRIV-sample",
    privateSecret: "b013f26f-329a-4156-a01c-38263505f965",
    smsText: "hello",
    senderNumber: "+16543219870",
    receiverNumber: "+16543219871",
    chatText: "hi",
    chatReceiverId: "user2@project.name.domain.com",
    setStatusPresence: "Busy",
    presentityUserId: "user2@domain.com",
    primaryContact: "user2@domain.com",
    firstName: "Tony",
    lastName: "Stark",
    emailAddress: "user2@domain.com",
    homePhoneNumber: "+16543219873",
    businessPhoneNumber: "+16543219874",
    buddy: "true",
    contactId: "user3@domain.com",
    searchFirstName: "user3",
    callToUser: "sip:user2@project.name.domain.com",
    smsVerificationNumber: '+16543219875',
    emailVerificationId: 'user2@domain.com',
    projectNameSecondUser: "PUB-project.name",
    usernameSecondUser: "user2@domain.com",
    passwordSecondUser: "Test@123",
    userFirst: "Tony",
    userSecond: "Bruce"
};