// @file preferences.js
var Preferences = {
    toMonitor: false,
    passwordGrant:true,
    enableSMS: true,
    enableChat: true,
    enablePresence: true,
    enableAddressBook: true,
    enableVoice: false,
    baseUrl: "nvs-cpaas-oauth.kandy.io",
    projectName: "PUB-test.ojfs",
    username: "vikas07@mail-cart.com",
    password: "Test@123",
    privateKey:  "PRIV-sample1",
    privateSecret: "b013f26f-329a-4156-a01c-38263505f965",
    smsText: "hello",
    senderNumber: "+12074666511",
    receiverNumber: "+17433333068",
    chatText: "hi",
    chatReceiverId: "arti07@test.ojfs.att.com",
    setStatusPresence: "Busy",
    presentityUserId: "arti07@mail-cart.com",
    primaryContact: "arti07@mail-cart.com",
    firstName: "ashish",
    lastName: "ashish",
    emailAddress: "arti07@mail-cart.com",
    homePhoneNumber: "+12074666511",
    businessPhoneNumber: "+17144850453",
    buddy: "true",
    contactId: "ashish@lx.in",
    searchFirstName: "ashish",
    callToUser: "sip:arti07@test.ojfs.att.com",
    smsVerificationNumber: '+19549510743',
    emailVerificationId: 'arti07@mail-cart.com',
    projectNameSecondUser: "PUB-test.ojfs",
    usernameSecondUser: "arti07@mail-cart.com",
    passwordSecondUser: "Test@123",
    userFirst: 'userFirst',
    userSecond: 'userSecond'
};