// @file preferences.js
var Preferences = {
    toMonitor: false,
    enableSMS: true,
    enableChat: true,
    enablePresence: true,
    enableAddressBook: true,
    baseUrl: "nvs-cpaas-oauth.kandy.io",
    projectName: "PUB-hcl107.MPb0QLfe",//   "PUB-My First Project",// "PUB-My Sms Project 2",
    username: "ashish07@idx4.com",// "d3smc2e0j3srxx0g",
    password: "test123",//"3E7pCDsFqY1fn4p4",
    smstext: "hello",
    sendernumber: "+12074666511",
    receivernumber: "+17433333068",
    chattext: "hi",
    chatreceiverid: "ashish07@hcl107.MPb0QLfe.att.com",
    setstatuspresence: "Busy",
    presentityUserId: "ashish07@idx4.com",
    primaryContact: "ashish07@idx4.com",
    firstName: "ashish",
    lastName: "ashish",
    emailAddress: "email",
    homePhoneNumber: "home",
    businessPhoneNumber: "business",
    buddy: "true",
    contactId: "ashish0090",
    searchfirstname:"ashish"
};